kind: Service
apiVersion: v1
metadata:
  name: kubernetes
spec:
  type: LoadBalancer
  selector:
    app: kubernetes
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: nemidevops/kubernetes:latest
